#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

mkdir -p reference && ./generate_reference.py

runApplication blockMesh

runApplication crystalBuoyantPbePimpleFoam

for t in $(foamListTimes -withZero); do
    runApplication -s $t reconstructPointDistribution -time $t
done

( cd imgs && ./createGraphs )

# ----------------------------------------------------------------- end-of-file
