#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

mkdir -p reference && ./generate_reference.py

runApplication blockMesh

runApplication crystalBuoyantPbePimpleFoam

( cd imgs && ./createGraphs )

# ----------------------------------------------------------------- end-of-file
