#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

runApplication blockMesh
runApplication decomposePar
runApplication crystalBuoyantPbePimpleFoam
runParallel crystalBuoyantPbePimpleFoam 8
runApplication reconstructPar

# ----------------------------------------------------------------- end-of-file