#!/bin/sh
cd ${0%/*} || exit 1

for solver in */; do
    [ -d "$solver/Make" ] || continue

    echo "========================================"
    echo "Building ${solver%/}"
    echo "========================================"

    (
        cd "$solver" || exit 1
        wmake
    ) || exit 1
done